x-environment: &environment
  env_file:
    - path: ./.env.example
      required: true
    - path: ./.env
      required: false

networks:
  rees46:
    name: rees46
    driver: bridge

services:
  ai-analyst:
    <<: *environment
    image: ghcr.io/rees46/ai-analyst:latest
    build:
      context: .
      target: dev
    profiles:
      - ''
    networks:
      - rees46
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./uv.lock
