[project]
name = "ai-analyst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "clickhouse-connect==0.8.18",
    "pandas==2.2.3",
    "langchain>=1.2.0",
    "langchain-community==0.4.1",
    "langchain-core==1.2.16",
    "langchain-experimental==0.4.1",
    "langchain-huggingface==1.2.0",
    "langchain-openai==1.1.10",
    "langchain-text-splitters==1.1.1",
    "langgraph==1.0.9",
    "langgraph-checkpoint==4.0.0",
    "langgraph-prebuilt==1.0.8",
    "langgraph-sdk==0.3.9",
    "faiss-cpu==1.13.2",
    "sentence-transformers==5.0.0",
    "python-telegram-bot==22.6",
    "python-dotenv==1.1.1",
    "pydantic==2.11.10",
    "pydantic-settings>=2.0.0",
    "psycopg2-binary>=2.9.9",
    "httpx==0.28.1",
    "httpx[socks]==0.28.1",
    "matplotlib>=3.7.0",
    "openpyxl>=3.1.0",
]
